### ISSUE TITLE
大佬好，请教一下关于embedding 的问题

### ISSUE THREAD

**Issue by yuemengrui** [percent4/document_qa_with_llm#1]
def get_text_embedding(req_text):
    url = "http://10.241.132.209:8000/v1/embeddings"
    headers = {'Content-Type': 'application/json'}
    payload = json.dumps({"model": "Baichuan-13B-Chat", "input": req_text})
    new_req = requests.request("POST", url, headers=headers, data=payload)
    return new_req.json()['data'][0]['embedding']

我看到代码中的embedding是用的baichuan-13b, 这个模型的embedding是怎么做到的，baichuan好像没有开放embedding模型.

**Comment by percent4** [comment]
> def get_text_embedding(req_text):
>     url = "http://10.241.132.209:8000/v1/embeddings"
>     headers = {'Content-Type': 'application/json'}
>     payload = json.dumps({"model": "Baichuan-13B-Chat", "input": req_text})
>     new_req = requests.request("POST", url, headers=headers, data=payload)
>     return new_req.json()['data'][0]['embedding']
> 
> 我看到代码中的embedding是用的baichuan-13b, 这个模型的embedding是怎么做到的，baichuan好像没有开放embedding模型.

部署工具采用FastChat，部署好了之后就有对应的embedding功能了。

**Comment by yuemengrui** [comment]
> > def get_text_embedding(req_text):
> > url = "http://10.241.132.209:8000/v1/embeddings"
> > headers = {'Content-Type': 'application/json'}
> > payload = json.dumps({"model": "Baichuan-13B-Chat", "input": req_text})
> > new_req = requests.request("POST", url, headers=headers, data=payload)
> > return new_req.json()['data'][0]['embedding']
> > 我看到代码中的embedding是用的baichuan-13b, 这个模型的embedding是怎么做到的，baichuan好像没有开放embedding模型.
> 
> 部署工具采用FastChat，部署好了之后就有对应的embedding功能了。

感谢大佬🙏
