### ISSUE TITLE
messages格式

### ISSUE THREAD

**Issue by Beenle301** [percent4/document_qa_with_llm#4]
![image](https://github.com/percent4/document_qa_with_llm/assets/133933719/d4214095-bcd5-4414-a386-0a4a9a1504ac)
请问为啥我按照这个格式请求baichuan-13b-chat会报错呢
[
    {
        "role": "system",
        "content": "……"
    },
    {
        "role": "user",
        "content": "……"
    }
]

**Comment by percent4** [comment]
> ![image](https://user-images.githubusercontent.com/133933719/259612948-d4214095-bcd5-4414-a386-0a4a9a1504ac.png) 请问为啥我按照这个格式请求baichuan-13b-chat会报错呢 [ { "role": "system", "content": "……" }, { "role": "user", "content": "……" } ]

这是我自己调用百川模型进行对话的内容（/v1/chat/completions）：

```json
{
    "model": "Baichuan-13B-Chat",
    "messages": [
        {
            "role": "user",
            "content": "给定以下标签：['不确定', '夫妻', '父母', '兄弟姐妹', '上下级', '师生', '好友', '同学', '合作', '同一个人', '情侣', '祖孙', '同门', '亲戚']，请在以下句子中分析并分类实体之间的关系：'1837年6月20日，威廉四世辞世，他的侄女维多利亚即位。'在这个句子中，威廉四世和维多利亚之间的关系应该属于哪个标签？"
        }
    ]
}
```

你应该忘记加model这个参数了。
